// Currency
export const SWAP_CURRENCY = 'SWAP_CURRENCY';
export const CHANGE_CHURRENCY_AMOUNT = 'CHANGE_CHURRENCY_AMOUNT';
export const CHANGE_BASE_CURRENCY = 'CHANGE_BASE_CURRENCY';
export const CHANGE_QUOTE_CURRENCY = 'CHANGE_QUOTE_CURRENCY';

// Conversion
export const GET_INITIAL_CONVERSION = 'GET_INITIAL_CONVERSION';
export const CONVERSION_ERROR = 'CONVERSION_ERROR';
export const CONVERSION_SUCCESS = 'CONVERSION_SUCCESS';

// Theme
export const CHANGE_THEME_COLOR = 'CHANGE_THEME_COLOR';
