// Currencies
export const SWAP_CURRENCY = 'SWAP_CURRENCY';
export const CHANGE_CHURRENCY_AMOUNT = 'CHANGE_CHURRENCY_AMOUNT';
export const CHANGE_BASE_CURRENCY = 'CHANGE_BASE_CURRENCY';
export const CHANGE_QUOTE_CURRENCY = 'CHANGE_QUOTE_CURRENCY';

// Theme
export const CHANGE_THEME_COLOR = 'CHANGE_THEME_COLOR';
